INSERT INTO stock (name, symbol) VALUES
('American Airlines Group, Inc' , 'AAL'),
('Apple Inc.','AAPL'),
('ABB Ltd.','ABB'),
('Accenture Plc.','ACN'),
('Adobe Systems Incorporated','ADBE'),
('Aerojet Rocketdyne Holdings, Inc.','AJRD'),
('Amazon.com, Inc.','AMZN'),
('Aon Plc.','AON'),
('Apache Corporation','APA'),
('Alpha Pro Tech, Ltd.','APT'),
('Activision Blizzard, Inc.','ATVI'),
('American Express Company','AXP'),
('Boeing Company','BA'),
('Tesla, Inc.','TSLA'),
('NVIDIA Corporation','NVDA'),
('Zoom Video Communications, Inc.','ZM'),
('Black Diamond Therapeutics, Inc.','BDTX'),
('BlackRock Capital Investment Corp.','BKCC'),
('Citigroup, Inc.','C'),
('Deere & Company','DE'),
('Enterprise Products Partners L.P.','EPD');